# Generated by Django 3.1.5 on 2021-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_ingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(null=True, to='recipe.Ingredient'),
        ),
    ]
