# Generated by Django 3.1.5 on 2021-09-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20210926_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
