# Generated by Django 3.1.5 on 2021-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20210927_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
