# Generated by Django 3.1.5 on 2021-09-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20210927_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='ユーザ名名'),
        ),
    ]
