# Generated by Django 3.1.5 on 2021-09-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20210929_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='ユーザ名'),
        ),
    ]
