# Generated by Django 3.1.5 on 2021-10-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_auto_20211009_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='favorite_recipes',
            field=models.ManyToManyField(related_name='favorite_users', to='recipe.Recipe'),
        ),
    ]
