# Generated by Django 3.1.5 on 2022-03-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_auto_20211022_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
