# Generated by Django 3.1.5 on 2022-05-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0021_ingredient_hiragana_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='api_recipe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
