# Generated by Django 3.1.5 on 2022-05-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_recipe_api_recipe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='api_recipe_id',
            new_name='api_id',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_time',
            new_name='cooking_time',
        ),
    ]
